# values.yaml

replicaCount: 
  tokenHandler: 1
  mortgage: 2

image:
  tokenHandler:
    repository: nardisync/token-handler-microservice
    tag: latest
  mortgage:
    repository: nardisync/mortgage-microservice
    tag: latest


service:
  enabled: true
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080