apiVersion: v1
kind: Service
metadata:
  name: mortgage-microservice-service
spec:
  selector:
    app: mortgage-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
